staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jkmillerphoto_staging
  pool: 5
  username:
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: jkmillerphoto_production
  pool: 5
  username:
  password:
  host: localhost
